[package]

name = "dotenv"
version = "0.2.2"
authors = ["Santiago Lapresta <santiago.lapresta@gmail.com>"]
readme = "README.md"
keywords = ["environment", "env", "dotenv", "settings", "config"]
license = "MIT"
homepage = "https://github.com/slapresta/rust-dotenv"
repository = "https://github.com/slapresta/rust-dotenv"
description = "A `dotenv` implementation for Rust"

[dependencies]
regex = "*"
